name: "Infrastructure Validation Pipeline"

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code Repo
        uses: actions/checkout@v4.2.2

      - name: Configure Terraform Core Runtime Environment
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.5.7

      - name: Validate File Code Formatting Standards
        run: terraform fmt -check -recursive

      - name: Initialize & Validate Terraform Code
        run: |
          cd terraform/modules/aws_compute
          terraform init -backend=false
          terraform validate


